@echo off
chcp 65001 >nul
setlocal enabledelayedexpansion

REM ========================================
REM Windows CMD launcher for the stack
REM - Prompts for ports
REM - Writes .env in the same folder as this script
REM - Starts Docker Compose (docker-compose or docker compose)
REM ========================================

echo.
echo ========================================
echo    Docker Stack Configuration
echo ========================================
echo.

REM Resolve the folder where this script resides
set PROJECT_ROOT=%~dp0
set ENV_FILE=%PROJECT_ROOT%.env

REM Defaults (σύμφωνα με το documentation)
set DEFAULT_FRONTEND_PORT=3000
set DEFAULT_SPRING_PORT=8081
set DEFAULT_PHPMYADMIN_PORT=8082

REM Check Docker availability first
echo Checking Docker availability...
where docker >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo.
    echo ✗ ERROR: Docker is not installed or not in PATH.
    echo.
    echo Please:
    echo   - Install Docker Desktop for Windows
    echo   - Make sure Docker Desktop is running
    echo   - Restart your terminal after installation
    echo.
    pause
    exit /b 127
)

REM Check if Docker daemon is running
docker ps >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo.
    echo ✗ ERROR: Docker daemon is not running.
    echo.
    echo Please start Docker Desktop and try again.
    echo.
    pause
    exit /b 1
)
echo ✓ Docker is available and running
echo.

REM Check if .env already exists
if exist "%ENV_FILE%" (
    echo ⚠ WARNING: File .env already exists!
    echo.
    set /p OVERWRITE="Do you want to overwrite it? (Y/N): "
    if /i not "!OVERWRITE!"=="Y" (
        echo.
        echo Using existing .env file...
        goto skip_env_creation
    )
    echo.
)

REM Ask ports
echo Configure ports for the stack:
echo (Press ENTER to use default values)
echo.

REM Frontend Port
:ask_frontend
set FRONTEND_INPUT=
set /p FRONTEND_INPUT="  Frontend (Next.js) host port [default: %DEFAULT_FRONTEND_PORT%]: "
if "!FRONTEND_INPUT!"=="" (
    set FRONTEND_PORT=%DEFAULT_FRONTEND_PORT%
) else (
    call :validate_port "!FRONTEND_INPUT!" FRONTEND_PORT
    if "!FRONTEND_PORT!"=="" goto ask_frontend
)
echo     → Using frontend port: !FRONTEND_PORT!
echo.

REM Spring Boot Port
:ask_spring
set SPRING_INPUT=
set /p SPRING_INPUT="  Spring Boot (app) host port [default: %DEFAULT_SPRING_PORT%]: "
if "!SPRING_INPUT!"=="" (
    set SPRING_PORT=%DEFAULT_SPRING_PORT%
) else (
    call :validate_port "!SPRING_INPUT!" SPRING_PORT
    if "!SPRING_PORT!"=="" goto ask_spring
)
echo     → Using Spring Boot port: !SPRING_PORT!
echo.

REM phpMyAdmin Port - NOW PROMPTS USER
:ask_phpmyadmin
set PHPMYADMIN_INPUT=
set /p PHPMYADMIN_INPUT="  phpMyAdmin host port [default: %DEFAULT_PHPMYADMIN_PORT%]: "
if "!PHPMYADMIN_INPUT!"=="" (
    set PHPMYADMIN_PORT=%DEFAULT_PHPMYADMIN_PORT%
) else (
    call :validate_port "!PHPMYADMIN_INPUT!" PHPMYADMIN_PORT
    if "!PHPMYADMIN_PORT!"=="" goto ask_phpmyadmin
)
echo     → Using phpMyAdmin port: !PHPMYADMIN_PORT!
echo.

REM Check for port conflicts
echo Checking for port conflicts...
call :check_port_in_use !FRONTEND_PORT! "Frontend"
call :check_port_in_use !SPRING_PORT! "Spring Boot"
call :check_port_in_use !PHPMYADMIN_PORT! "phpMyAdmin"
echo.

REM Fixed DB config
set MYSQL_ROOT_PASSWORD=root
set MYSQL_DATABASE=mydb
set MYSQL_PORT=3306
set SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/!MYSQL_DATABASE!
set SPRING_DATASOURCE_USERNAME=root
set SPRING_DATASOURCE_PASSWORD=!MYSQL_ROOT_PASSWORD!
set NEXT_PUBLIC_API_URL=http://localhost

REM Show summary
echo ========================================
echo Configuration Summary:
echo ========================================
echo  Frontend:     http://localhost:!FRONTEND_PORT!
echo  Spring Boot:  http://localhost:!SPRING_PORT!
echo  phpMyAdmin:   http://localhost:!PHPMYADMIN_PORT!
echo  Database:     !MYSQL_DATABASE! (port: !MYSQL_PORT!)
echo  DB User:      !SPRING_DATASOURCE_USERNAME!
echo  API URL:      !NEXT_PUBLIC_API_URL!
echo ========================================
echo.
set /p CONFIRM="Continue with this configuration? (Y/N): "
if /i not "!CONFIRM!"=="Y" (
    echo.
    echo Cancelled by user.
    pause
    exit /b 0
)

REM Write .env next to the script
echo.
echo Creating .env file...
(
    echo # Generated by start.cmd on %DATE% %TIME%
    echo.
    echo # MySQL
    echo MYSQL_ROOT_PASSWORD=!MYSQL_ROOT_PASSWORD!
    echo MYSQL_DATABASE=!MYSQL_DATABASE!
    echo MYSQL_PORT=!MYSQL_PORT!
    echo.
    echo # Spring Boot datasource
    echo SPRING_DATASOURCE_URL=!SPRING_DATASOURCE_URL!
    echo SPRING_DATASOURCE_USERNAME=!SPRING_DATASOURCE_USERNAME!
    echo SPRING_DATASOURCE_PASSWORD=!SPRING_DATASOURCE_PASSWORD!
    echo.
    echo # Ports
    echo FRONTEND_PORT=!FRONTEND_PORT!
    echo SPRING_SERVER_PORT=!SPRING_PORT!
    echo PHPMYADMIN_PORT=!PHPMYADMIN_PORT!
    echo.
    echo # Frontend API Configuration
    echo NEXT_PUBLIC_API_URL=!NEXT_PUBLIC_API_URL!
) > "%ENV_FILE%"

if exist "%ENV_FILE%" (
    echo ✓ Created: %ENV_FILE%
) else (
    echo ✗ ERROR: Failed to create .env file
    pause
    exit /b 1
)
echo.

:skip_env_creation

REM Detect docker compose command
where docker-compose >nul 2>nul
if %ERRORLEVEL%==0 (
    set COMPOSE_CMD=docker-compose
    echo Using: docker-compose
) else (
    set COMPOSE_CMD=docker compose
    echo Using: docker compose
)

echo.
echo ========================================
echo Starting Docker Compose...
echo ========================================
echo.
echo This may take a few minutes on first run...
echo.

cd /d "%PROJECT_ROOT%"
%COMPOSE_CMD% up --build

if %ERRORLEVEL% NEQ 0 (
    echo.
    echo ========================================
    echo ✗ Docker Compose failed
    echo ========================================
    echo.
    echo Common issues:
    echo   - Ports already in use: Run script again with different ports
    echo   - File sharing not enabled: Enable in Docker Desktop Settings
    echo   - Network issues: Check your internet connection
    echo.
    pause
    exit /b %ERRORLEVEL%
)

exit /b 0

REM ========================================
REM Subroutines
REM ========================================

:validate_port
set "INPUT_VAL=%~1"
set "OUTPUT_VAR=%~2"

REM Remove quotes if any
set INPUT_VAL=%INPUT_VAL:"=%

REM Check if empty
if "%INPUT_VAL%"=="" (
    echo     ✗ Invalid: Empty value. Try again.
    set "%OUTPUT_VAR%="
    goto :eof
)

REM Check if numeric (using a different approach)
set "TESTVAL=%INPUT_VAL%"
set "NUMERIC=1"

REM Check each character
:check_numeric_loop
if not defined TESTVAL goto check_numeric_done
set "CHAR=%TESTVAL:~0,1%"
set "TESTVAL=%TESTVAL:~1%"

REM Check if character is 0-9
echo %CHAR%| findstr /r "^[0-9]$" >nul
if errorlevel 1 (
    set "NUMERIC=0"
    goto check_numeric_done
)
goto check_numeric_loop

:check_numeric_done
if "%NUMERIC%"=="0" (
    echo     ✗ Invalid: '%INPUT_VAL%' is not a number. Try again.
    set "%OUTPUT_VAR%="
    goto :eof
)

REM Check range (1-65535)
if %INPUT_VAL% LSS 1 (
    echo     ✗ Invalid: Port must be between 1-65535. Try again.
    set "%OUTPUT_VAR%="
    goto :eof
)
if %INPUT_VAL% GTR 65535 (
    echo     ✗ Invalid: Port must be between 1-65535. Try again.
    set "%OUTPUT_VAR%="
    goto :eof
)

REM Warn for reserved ports
if %INPUT_VAL% LSS 1024 (
    echo     ⚠ Warning: Port %INPUT_VAL% is in reserved range (1-1023^)
    set /p WARNING_CONFIRM="       Continue anyway? (Y/N): "
    if /i not "!WARNING_CONFIRM!"=="Y" (
        set "%OUTPUT_VAR%="
        goto :eof
    )
)

set "%OUTPUT_VAR%=%INPUT_VAL%"
goto :eof

:check_port_in_use
set CHECK_PORT=%~1
set SERVICE_NAME=%~2

netstat -ano | findstr ":%CHECK_PORT% " | findstr "LISTENING" >nul 2>nul
if %ERRORLEVEL%==0 (
    echo   ⚠ Warning: Port %CHECK_PORT% (%SERVICE_NAME%^) appears to be in use!
    echo      You may need to choose a different port or stop the conflicting service.
)
goto :eof