@echo off
setlocal enabledelayedexpansion

REM Windows CMD launcher for the stack
REM - Prompts for ports
REM - Writes .env in the same folder as this script
REM - Starts Docker Compose (docker-compose or docker compose)

REM Resolve the folder where this script resides
set PROJECT_ROOT=%~dp0
set ENV_FILE=%PROJECT_ROOT%.env

REM Defaults
set DEFAULT_SPRING_PORT=8081
set DEFAULT_MYSQL_PORT=3306
set DEFAULT_PHPMYADMIN_PORT=8082

REM Read port with validation (2-5 digits)
:read_port
set PROMPT=%~1
set DEFAULT=%~2
:read_loop
set /p INPUT=%PROMPT% [default: %DEFAULT%]:
if "%INPUT%"=="" set INPUT=%DEFAULT%
for /f "tokens=1" %%A in ("%INPUT%") do set VAL=%%A
for /f "tokens=1 delims=0123456789" %%B in ("%VAL%") do set NONNUM=%%B
if "%NONNUM%"=="" (
  if not "%VAL%"=="" (
    set PORT_OUT=%VAL%
    goto :read_done
  )
)
echo Invalid port: '%INPUT%'. Please enter a numeric port (e.g., 8080).
goto :read_loop
:read_done

REM Ask ports
call :read_port "Enter Spring Boot (app) host port" %DEFAULT_SPRING_PORT%
set SPRING_PORT=%PORT_OUT%
call :read_port "Enter MySQL host port" %DEFAULT_MYSQL_PORT%
set MYSQL_PORT=%PORT_OUT%
call :read_port "Enter phpMyAdmin host port" %DEFAULT_PHPMYADMIN_PORT%
set PHPMYADMIN_PORT=%PORT_OUT%

REM Fixed DB config
set MYSQL_ROOT_PASSWORD=root
set MYSQL_DATABASE=mydb
set SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/%MYSQL_DATABASE%
set SPRING_DATASOURCE_USERNAME=root
set SPRING_DATASOURCE_PASSWORD=%MYSQL_ROOT_PASSWORD%

REM Write .env next to the script
>"%ENV_FILE%" echo # Generated by start.cmd on %DATE% %TIME%
>>"%ENV_FILE%" echo.
>>"%ENV_FILE%" echo # MySQL
>>"%ENV_FILE%" echo MYSQL_ROOT_PASSWORD=%MYSQL_ROOT_PASSWORD%
>>"%ENV_FILE%" echo MYSQL_DATABASE=%MYSQL_DATABASE%
>>"%ENV_FILE%" echo MYSQL_PORT=%MYSQL_PORT%
>>"%ENV_FILE%" echo.
>>"%ENV_FILE%" echo # Spring Boot datasource
>>"%ENV_FILE%" echo SPRING_DATASOURCE_URL=%SPRING_DATASOURCE_URL%
>>"%ENV_FILE%" echo SPRING_DATASOURCE_USERNAME=%SPRING_DATASOURCE_USERNAME%
>>"%ENV_FILE%" echo SPRING_DATASOURCE_PASSWORD=%SPRING_DATASOURCE_PASSWORD%
>>"%ENV_FILE%" echo.
>>"%ENV_FILE%" echo # Ports
>>"%ENV_FILE%" echo SPRING_SERVER_PORT=%SPRING_PORT%
>>"%ENV_FILE%" echo PHPMYADMIN_PORT=%PHPMYADMIN_PORT%

echo Wrote environment file: %ENV_FILE%

REM Detect docker compose command
where docker-compose >nul 2>nul
if %ERRORLEVEL%==0 (
  set COMPOSE_CMD=docker-compose
) else (
  where docker >nul 2>nul
  if not %ERRORLEVEL%==0 (
    echo Error: docker is not installed or not in PATH.
    exit /b 127
  )
  set COMPOSE_CMD=docker compose
)

cd "%PROJECT_ROOT%"
echo Starting Docker Compose build and up...
%COMPOSE_CMD% up --build
exit /b %ERRORLEVEL%

